# Без авторизации
auth-enabled: false

# HTTP сервер слушает порт 3100
server:
  http_listen_port: 3100

# Ingester (приёмщик логов)
# Управление жизненным циклом и хранением чанков (частей логов). replication_factor: 1 - без репликации.
# Тайминги: idle 5m, retain 30s.
ingester:
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: summary
      replication_factor: 1
    final_sleep: 0s
    chunk_idle_period: 5m
    chunk_retain_period: 30s
    max_transfer_retries: 0

# Schema / Storage
# История с 2018-04-15, схема хранения v11.
# Индексы - в boltdb (/loki/index).
# Логи (чанки) - в файловой системе (/loki/chunks).
schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: loki/index
  filesystem:
    directory: loki/chunks

# Limits
# Ограничения по приёму логов: до 8 MB/s, burst до 10 МВ.
# Отбрасываются слишком старые записи (старше 168h).
limits_config:
  enforce_metrics_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 10

# Chunk storage
# max_look_back_period: Os -> без ограничения по времени на поиск в чанках.
chunk_storage_config:
  max_look_back_period: 0s

# Table Manager
# Управляет таблицами индексов и чанков.
# Retention: хранение логов 672h (~28 дней).
# Автоматические удаления включены.
table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: true
  retention period: 672h
